repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ^frontend/
      - id: end-of-file-fixer
        files: ^frontend/
      - id: check-yaml
        files: ^frontend/
      - id: check-added-large-files
        files: ^frontend/
      - id: check-merge-conflict
        files: ^frontend/
      - id: check-json
        files: ^frontend/.*\.json$
      - id: mixed-line-ending
        files: ^frontend/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|ts|vue|json|css|scss|html|md)$
        additional_dependencies:
          - prettier@3.6.2

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0
    hooks:
      - id: eslint
        files: ^frontend/.*\.(js|ts|vue)$
        additional_dependencies:
          - eslint@^9.33.0
          - eslint-plugin-vue@~10.4.0
          - '@vue/eslint-config-prettier@^10.2.0'
          - '@vue/eslint-config-typescript@^14.6.0'
          - '@vitest/eslint-plugin@^1.3.13'
        args: ["--fix"]

  - repo: local
    hooks:
      - id: vue-tsc
        name: vue-tsc type check
        entry: bash -c 'cd frontend && npm run type-check'
        language: system
        files: ^frontend/.*\.(ts|vue)$
        pass_filenames: false
        always_run: false
      - id: vitest
        name: vitest unit tests
        entry: bash -c 'cd frontend && npm run test:unit run'
        language: system
        files: ^frontend/(src|tests)/.*\.(ts|vue)$
        pass_filenames: false
        always_run: false
