"""
This type stub file was generated by pyright.
"""

from typing import Any

"""Type stubs for ibapi.client - TWS API client interface."""
class EClient:
    """Base class for TWS API client requests."""
    conn: Any
    msg_queue: Any
    def __init__(self, wrapper: Any) -> None:
        """Initialize client with wrapper."""
        ...
    
    def connect(self, host: str, port: int, clientId: int) -> None:
        """Connect to TWS/Gateway."""
        ...
    
    def disconnect(self) -> None:
        """Disconnect from TWS/Gateway."""
        ...
    
    def run(self) -> None:
        """Run message loop (blocking)."""
        ...
    
    def reqMatchingSymbols(self, reqId: int, pattern: str) -> None:
        """Request symbol search."""
        ...
    
    def reqContractDetails(self, reqId: int, contract: Any) -> None:
        """Request contract details."""
        ...
    
    def reqHistoricalData(self, reqId: int, contract: Any, endDateTime: str, durationStr: str, barSizeSetting: str, whatToShow: str, useRTH: int, formatDate: int, keepUpToDate: bool, chartOptions: list[Any]) -> None:
        """Request historical data."""
        ...
    
    def reqRealTimeBars(self, reqId: int, contract: Any, barSize: int, whatToShow: str, useRTH: bool, realTimeBarsOptions: list[Any]) -> None:
        """Request real-time bars."""
        ...
    
    def reqMktData(self, reqId: int, contract: Any, genericTickList: str, snapshot: bool, regulatorySnapshot: bool, mktDataOptions: list[Any]) -> None:
        """Request market data."""
        ...
    
    def cancelRealTimeBars(self, reqId: int) -> None:
        """Cancel real-time bars subscription."""
        ...
    
    def cancelMktData(self, reqId: int) -> None:
        """Cancel market data subscription."""
        ...
    


