"""
This type stub file was generated by pyright.
"""

from decimal import Decimal

"""Type stubs for ibapi.common - TWS API common data types."""
class BarData:
    """OHLCV bar data from TWS."""
    date: str
    open: float
    high: float
    low: float
    close: float
    volume: Decimal
    wap: Decimal
    barCount: int
    def __init__(self) -> None:
        ...
    


