"""
This type stub file was generated by pyright.
"""

"""Type stubs for ibapi.contract - TWS API contract definitions."""
class Contract:
    """TWS contract specification."""
    symbol: str
    secType: str
    exchange: str
    currency: str
    localSymbol: str
    tradingClass: str
    conId: int
    def __init__(self) -> None:
        ...
    


class ContractDescription:
    """Contract description from symbol search."""
    contract: Contract
    derivativeSecTypes: list[str]
    def __init__(self) -> None:
        ...
    


class ContractDetails:
    """Detailed contract information."""
    contract: Contract
    marketName: str
    minTick: float
    orderTypes: str
    validExchanges: str
    priceMagnifier: int
    underConId: int
    longName: str
    contractMonth: str
    industry: str
    category: str
    subcategory: str
    timeZoneId: str
    tradingHours: str
    liquidHours: str
    def __init__(self) -> None:
        ...
    


