"""
This type stub file was generated by pyright.
"""

from typing import Any

"""Type stubs for ibapi.reader - TWS API message reader."""
class EReader:
    """Message reader for TWS API."""
    def __init__(self, conn: Any, msg_queue: Any) -> None:
        """Initialize reader."""
        ...
    
    def start(self) -> None:
        """Start reader thread."""
        ...
    


