"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from decimal import Decimal
from typing import Any

"""Type stubs for ibapi.wrapper - TWS API callback interface."""

class EWrapper:
    """Base class for TWS API callbacks.

    All callback methods are optional - override only what you need.
    """

    def nextValidId(self, orderId: int) -> None:
        """Called when connection is established."""
        ...

    def symbolSamples(self, reqId: int, contractDescriptions: Sequence[Any]) -> None:
        """Symbol search results callback."""
        ...

    def contractDetails(self, reqId: int, contractDetails: Any) -> None:
        """Contract details callback (multiple responses)."""
        ...

    def contractDetailsEnd(self, reqId: int) -> None:
        """Contract details end marker."""
        ...

    def historicalData(self, reqId: int, bar: Any) -> None:
        """Historical bar data callback (multiple responses)."""
        ...

    def historicalDataEnd(self, reqId: int, start: str, end: str) -> None:
        """Historical data end marker."""
        ...

    def realtimeBar(
        self,
        reqId: int,
        time: int,
        open_: float,
        high: float,
        low: float,
        close: float,
        volume: Decimal,
        wap: Decimal,
        count: int,
    ) -> None:
        """Real-time bar callback."""
        ...

    def tickPrice(self, reqId: int, tickType: int, price: float, attrib: Any) -> None:
        """Tick price update callback."""
        ...

    def tickSize(self, reqId: int, tickType: int, size: Decimal) -> None:
        """Tick size update callback."""
        ...

    def tickSnapshotEnd(self, reqId: int) -> None:
        """Tick snapshot end marker."""
        ...

    def error(
        self,
        reqId: int,
        errorTime: int,
        errorCode: int,
        errorString: str,
        advancedOrderRejectJson: str = ...,
    ) -> None:
        """Error callback."""
        ...
