repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
        files: ^(src|tests)/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(src|tests)/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^(src|tests)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        files: ^src/.*\.py$
        additional_dependencies: [pydantic]

  - repo: local
    hooks:
      - id: check-response-models
        name: Check FastAPI Response Models
        entry: python scripts/check_response_models.py
        language: system
        files: ^src/trading_api/api/.*\.py$
        pass_filenames: true