"""Type stubs for ibapi.decoder module."""

from types import MappingProxyType
from typing import Callable, Iterator

from click import Parameter
from ibapi.object_implem import Object
from ibapi.wrapper import EWrapper

class HandleInfo(Object):
    wrapperMeth: Callable | None
    wrapperParams: MappingProxyType[str, Parameter] | None
    processMeth: Callable | None
    def __init__(
        self, wrap: Callable | None = None, proc: Callable | None = None
    ) -> None: ...
    def __str__(self) -> str: ...

class Decoder(Object):
    wrapper: EWrapper
    serverVersion: int
    msgId2handleInfo: dict[int, HandleInfo]
    msgId2handleInfoProtoBuf: dict[int, HandleInfo]

    def __init__(self, wrapper: EWrapper, serverVersion: int) -> None: ...
    def discoverParams(self) -> None: ...
    def printParams(self) -> None: ...
    def interpretWithSignature(
        self, fields: list[bytes], handleInfo: HandleInfo
    ) -> None: ...
    def interpret(self, fields: list[bytes], msgId: int) -> None: ...
    def processProtoBuf(self, protoBuf: bytes, msgId: int) -> None: ...

    # Process methods (private, but included for completeness)
    def processTickPriceMsg(self, fields: Iterator[bytes]) -> None: ...
    def processTickSizeMsg(self, fields: Iterator[bytes]) -> None: ...
    def processOrderStatusMsg(self, fields: Iterator[bytes]) -> None: ...
    def processOrderStatusMsgProtoBuf(self, protobuf: bytes) -> None: ...
    def processOpenOrder(self, fields: Iterator[bytes]) -> None: ...
    def processOpenOrderMsgProtoBuf(self, protobuf: bytes) -> None: ...
    def processOpenOrdersEndMsgProtoBuf(self, protobuf: bytes) -> None: ...
    def processPortfolioValueMsg(self, fields: Iterator[bytes]) -> None: ...
    def processContractDataMsg(self, fields: Iterator[bytes]) -> None: ...
    def processBondContractDataMsg(self, fields: Iterator[bytes]) -> None: ...
    def processScannerDataMsg(self, fields: Iterator[bytes]) -> None: ...
    def processExecutionDataMsg(self, fields: Iterator[bytes]) -> None: ...
    def processExecutionDataMsgProtoBuf(self, protobuf: bytes) -> None: ...
    def processExecutionDataEndMsgProtoBuf(self, protobuf: bytes) -> None: ...
    def processHistoricalDataMsg(self, fields: Iterator[bytes]) -> None: ...
    def processHistoricalDataEndMsg(self, fields: Iterator[bytes]) -> None: ...
    def processHistoricalDataUpdateMsg(self, fields: Iterator[bytes]) -> None: ...
    def processRealTimeBarMsg(self, fields: Iterator[bytes]) -> None: ...
    def processTickOptionComputationMsg(self, fields: Iterator[bytes]) -> None: ...
    def processDeltaNeutralValidationMsg(self, fields: Iterator[bytes]) -> None: ...
    def processMarketDataTypeMsg(self, fields: Iterator[bytes]) -> None: ...
    def processCommissionAndFeesReportMsg(self, fields: Iterator[bytes]) -> None: ...
    def processPositionDataMsg(self, fields: Iterator[bytes]) -> None: ...
    def processPositionMultiMsg(self, fields: Iterator[bytes]) -> None: ...
    def processSecurityDefinitionOptionParameterMsg(
        self, fields: Iterator[bytes]
    ) -> None: ...
    def processSecurityDefinitionOptionParameterEndMsg(
        self, fields: Iterator[bytes]
    ) -> None: ...
    def processSoftDollarTiersMsg(self, fields: Iterator[bytes]) -> None: ...
    def processFamilyCodesMsg(self, fields: Iterator[bytes]) -> None: ...
    def processSymbolSamplesMsg(self, fields: Iterator[bytes]) -> None: ...
    def processSmartComponents(self, fields: Iterator[bytes]) -> None: ...
    def processTickReqParams(self, fields: Iterator[bytes]) -> None: ...
    def processMktDepthExchanges(self, fields: Iterator[bytes]) -> None: ...
    def processHeadTimestamp(self, fields: Iterator[bytes]) -> None: ...
    def processTickNews(self, fields: Iterator[bytes]) -> None: ...
    def processNewsProviders(self, fields: Iterator[bytes]) -> None: ...
    def processNewsArticle(self, fields: Iterator[bytes]) -> None: ...
    def processHistoricalNews(self, fields: Iterator[bytes]) -> None: ...
    def processHistoricalNewsEnd(self, fields: Iterator[bytes]) -> None: ...
    def processHistogramData(self, fields: Iterator[bytes]) -> None: ...
    def processRerouteMktDataReq(self, fields: Iterator[bytes]) -> None: ...
    def processRerouteMktDepthReq(self, fields: Iterator[bytes]) -> None: ...
    def processMarketRuleMsg(self, fields: Iterator[bytes]) -> None: ...
    def processPnLMsg(self, fields: Iterator[bytes]) -> None: ...
    def processPnLSingleMsg(self, fields: Iterator[bytes]) -> None: ...
    def processHistoricalTicks(self, fields: Iterator[bytes]) -> None: ...
    def processHistoricalTicksBidAsk(self, fields: Iterator[bytes]) -> None: ...
    def processHistoricalTicksLast(self, fields: Iterator[bytes]) -> None: ...
    def processTickByTickMsg(self, fields: Iterator[bytes]) -> None: ...
    def processOrderBoundMsg(self, fields: Iterator[bytes]) -> None: ...
    def processMarketDepthMsg(self, fields: Iterator[bytes]) -> None: ...
    def processMarketDepthL2Msg(self, fields: Iterator[bytes]) -> None: ...
    def processCompletedOrderMsg(self, fields: Iterator[bytes]) -> None: ...
    def processCompletedOrdersEndMsg(self, fields: Iterator[bytes]) -> None: ...
    def processReplaceFAEndMsg(self, fields: Iterator[bytes]) -> None: ...
    def processWshMetaDataMsg(self, fields: Iterator[bytes]) -> None: ...
    def processWshEventDataMsg(self, fields: Iterator[bytes]) -> None: ...
    def processHistoricalSchedule(self, fields: Iterator[bytes]) -> None: ...
    def processUserInfo(self, fields: Iterator[bytes]) -> None: ...
    def processCurrentTimeInMillis(self, fields: Iterator[bytes]) -> None: ...
    def processErrorMsg(self, fields: Iterator[bytes]) -> None: ...
    def processErrorMsgProtoBuf(self, protobuf: bytes) -> None: ...
